insert into autores (id, nombre, email, imagen) values ('1', 'Noella', 'ndafter1@w3.org', 'http://dummyimage.com/161x100.png/ff4444/ffffff');
insert into autores (id, nombre, email, imagen) values ('2', 'Garth', 'gwindrum7@vkontakte.ru', 'http://dummyimage.com/187x100.png/dddddd/000000');
insert into autores (id, nombre, email, imagen) values ('3', 'Geralda', 'gdaubenya@yandex.ru', 'http://dummyimage.com/214x100.png/cc0000/ffffff');
insert into autores (id, nombre, email, imagen) values ('4', 'Tad', 'tandererr@posterous.com', 'http://dummyimage.com/234x100.png/cc0000/ffffff');


insert into posts (id, titulo, descripcion, fecha, categoria, autor_id) values (1, 'venenatis lacinia aenean', 'dignissim vestibulum vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae nulla dapibus dolor vel est donec odio justo sollicitudin ut suscipit a feugiat et eros vestibulum ac est lacinia nisi venenatis tristique fusce congue diam id ornare imperdiet sapien urna pretium nisl ut volutpat sapien arcu sed augue aliquam erat volutpat in congue etiam justo etiam pretium iaculis justo in hac habitasse platea', '2024-04-07', 'id nulla ultrices', 1);
insert into posts (id, titulo, descripcion, fecha, categoria, autor_id) values (2, 'ut ultrices vel', 'et ultrices posuere cubilia curae duis faucibus accumsan odio curabitur convallis duis consequat dui nec nisi volutpat eleifend donec ut dolor morbi vel lectus in quam fringilla rhoncus mauris enim leo rhoncus sed vestibulum sit amet cursus id turpis integer aliquet massa id lobortis convallis tortor risus dapibus augue vel accumsan tellus nisi eu orci mauris lacinia sapien quis libero nullam sit', '2023-07-19', 'donec', 2);
insert into posts (id, titulo, descripcion, fecha, categoria, autor_id) values (3, 'dolor sit amet consectetuer', 'consequat lectus in est risus auctor sed tristique in tempus sit amet sem fusce consequat nulla nisl nunc nisl duis bibendum felis sed interdum venenatis turpis enim blandit mi in porttitor pede justo eu massa donec dapibus duis at velit eu est congue elementum in hac habitasse platea dictumst morbi vestibulum velit id', '2024-02-04', 'sem', 3);
insert into posts (id, titulo, descripcion, fecha, categoria, autor_id) values (4, 'turpis integer aliquet massa id lobortis con', 'quis libero nullam sit amet turpis elementum ligula vehicula consequat morbi a ipsum integer a nibh in quis justo maecenas rhoncus aliquam lacus morbi quis tortor id nulla ultrices aliquet maecenas leo odio condimentum id luctus nec molestie sed justo pellentesque viverra pede ac diam cras pellentesque volutpat dui maecenas tristique est et tempus semper est quam pharetra magna ac consequat metus sapien ut nunc vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere', '2023-08-23', 'turpis eget elit', 1);
insert into posts (id, titulo, descripcion, fecha, categoria, autor_id) values (5, 'amet eleifend pede', 'metus arcu adipiscing molestie hendrerit at vulputate vitae nisl aenean lectus pellentesque eget nunc donec quis orci eget orci vehicula condimentum curabitur in libero ut massa volutpat convallis morbi odio odio elementum eu interdum eu tincidunt in leo maecenas pulvinar lobortis est phasellus sit amet erat nulla tempus vivamus in felis eu sapien cursus vestibulum proin eu mi nulla ac enim in', '2023-10-22', 'vel lectus in', 2);
insert into posts (id, titulo, descripcion, fecha, categoria, autor_id) values (6, 'habitasse platea dictumst morbi vestibulum', 'adipiscing elit proin risus praesent lectus vestibulum quam sapien varius ut blandit non interdum in ante vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae duis faucibus accumsan odio curabitur convallis duis consequat dui nec nisi volutpat eleifend donec ut dolor morbi vel lectus in quam fringilla rhoncus mauris enim leo rhoncus sed vestibulum sit', '2023-08-30', 'amet sem', 3);
insert into posts (id, titulo, descripcion, fecha, categoria, autor_id) values (7, 'ac consequat metus sapien', 'massa id nisl venenatis lacinia aenean sit amet justo morbi ut odio cras mi pede malesuada in imperdiet et commodo vulputate justo in blandit ultrices enim lorem ipsum dolor sit amet consectetuer adipiscing elit proin interdum mauris non ligula pellentesque ultrices phasellus id sapien in sapien iaculis congue vivamus metus arcu adipiscing molestie hendrerit at vulputate vitae nisl aenean lectus pellentesque eget nunc donec quis orci eget', '2023-09-14', 'fusce congue', 1);
insert into posts (id, titulo, descripcion, fecha, categoria, autor_id) values (8, 'ultrices posuere cubilia curae', 'aenean lectus pellentesque eget nunc donec quis orci eget orci vehicula condimentum curabitur in libero ut massa volutpat convallis morbi odio odio elementum eu interdum eu tincidunt in leo maecenas pulvinar lobortis est phasellus sit amet erat nulla tempus vivamus in felis eu sapien cursus vestibulum proin eu mi nulla ac enim in tempor turpis nec euismod scelerisque quam turpis adipiscing lorem vitae mattis nibh ligula nec sem duis aliquam convallis nunc proin at turpis a pede posuere', '2023-06-29', 'auctor', 2);
insert into posts (id, titulo, descripcion, fecha, categoria, autor_id) values (9, 'bibendum morbi non quam nec dui luctus', 'luctus ultricies eu nibh quisque id justo sit amet sapien dignissim vestibulum vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae nulla dapibus dolor vel est donec odio justo sollicitudin ut suscipit a feugiat et eros vestibulum ac est lacinia nisi venenatis tristique fusce congue diam id ornare imperdiet sapien urna pretium nisl ut volutpat sapien arcu sed augue aliquam', '2024-01-12', 'nibh in', 4);
insert into posts (id, titulo, descripcion, fecha, categoria, autor_id) values (10, 'et ultrices posuere', 'pellentesque eget nunc donec quis orci eget orci vehicula condimentum curabitur in libero ut massa volutpat convallis morbi odio odio elementum eu interdum eu tincidunt in leo maecenas pulvinar lobortis est phasellus sit amet erat nulla tempus vivamus in felis eu sapien cursus vestibulum proin eu mi nulla ac enim in tempor turpis nec euismod scelerisque quam', '2024-01-15', 'sed ante vivamus', 1);
insert into posts (id, titulo, descripcion, fecha, categoria, autor_id) values (11, 'mauris sit amet', 'sapien quis libero nullam sit amet turpis elementum ligula vehicula consequat morbi a ipsum integer a nibh in quis justo maecenas rhoncus aliquam lacus morbi quis tortor id nulla ultrices aliquet maecenas leo odio condimentum id luctus nec molestie sed justo pellentesque viverra pede ac diam cras pellentesque volutpat dui maecenas tristique est et tempus semper est quam pharetra magna ac consequat metus sapien ut nunc vestibulum ante ipsum primis in', '2023-07-02', 'quis orci', 2);
insert into posts (id, titulo, descripcion, fecha, categoria, autor_id) values (12, 'amet eleifend pede libero quis', 'integer pede justo lacinia eget tincidunt eget tempus vel pede morbi porttitor lorem id ligula suspendisse ornare consequat lectus in est risus auctor sed tristique in tempus sit amet sem fusce consequat nulla nisl nunc nisl duis bibendum felis sed interdum venenatis turpis enim blandit mi in porttitor pede justo eu massa donec dapibus duis at velit eu est congue elementum in hac habitasse platea dictumst morbi vestibulum velit id pretium iaculis diam erat fermentum justo nec condimentum', '2024-02-21', 'ut', 3);
insert into posts (id, titulo, descripcion, fecha, categoria, autor_id) values (13, 'at turpis a pede posuere nonummy', 'mauris viverra diam vitae quam suspendisse potenti nullam porttitor lacus at turpis donec posuere metus vitae ipsum aliquam non mauris morbi non lectus aliquam sit amet diam in magna bibendum imperdiet nullam orci pede venenatis non sodales sed tincidunt eu felis fusce posuere felis sed lacus morbi sem mauris laoreet ut rhoncus aliquet pulvinar sed nisl nunc rhoncus dui vel sem sed sagittis nam congue risus semper', '2024-02-29', 'ornare imperdiet sapien', 4);
insert into posts (id, titulo, descripcion, fecha, categoria, autor_id) values (14, 'et ultrices posuere cubilia curae duis', 'nisl duis bibendum felis sed interdum venenatis turpis enim blandit mi in porttitor pede justo eu massa donec dapibus duis at velit eu est congue elementum in hac habitasse platea dictumst morbi vestibulum velit id pretium iaculis diam erat fermentum justo nec condimentum neque sapien placerat ante nulla justo aliquam quis turpis eget elit sodales scelerisque mauris sit amet eros suspendisse accumsan tortor quis turpis', '2023-07-29', 'pellentesque quisque', 1);
insert into posts (id, titulo, descripcion, fecha, categoria, autor_id) values (15, 'eget vulputate ut ultrices vel', 'et commodo vulputate justo in blandit ultrices enim lorem ipsum dolor sit amet consectetuer adipiscing elit proin interdum mauris non ligula pellentesque ultrices phasellus id sapien in sapien iaculis congue vivamus metus arcu adipiscing molestie hendrerit at vulputate vitae nisl aenean lectus pellentesque eget nunc donec quis orci eget orci vehicula condimentum curabitur in libero ut massa volutpat convallis morbi odio odio elementum eu interdum eu tincidunt in', '2023-07-31', 'faucibus orci luctus', 2);
